In [1]:
import pandas as pd
import numpy as np

# Compare AdjP < 0.01, no LFC cutoff

In [2]:
rna = pd.read_csv('Space_uG_over_Space_1G_rRNA.csv', index_col=0)
rna['logpvalue'] = -np.log10(rna['pvalue'])
rna.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,logpvalue
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.068078,9.457235e-01,9.961099e-01,0.024236
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.644889,2.091264e-14,1.650742e-12,13.679591
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.264598,2.060156e-01,6.826370e-01,0.686100
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.317572,2.047261e-02,1.950173e-01,1.688827
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.710761,4.772322e-01,NaN,0.321270

In [3]:
norna = pd.read_csv('Space_uG_over_Space_1G_no_rRNA.csv', index_col=0)
norna['logpvalue'] = -np.log10(norna['pvalue'])
norna.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,logpvalue
ENSMUSG00000000001,1113.772188,0.006149,0.090487,0.067959,9.458185e-01,9.944408e-01,0.024192
ENSMUSG00000000028,161.147872,1.394208,0.182351,7.645723,2.077750e-14,1.570749e-12,13.682407
ENSMUSG00000000031,25.889980,0.546685,0.432254,1.264730,2.059680e-01,6.689568e-01,0.686200
ENSMUSG00000000037,17.905616,1.129467,0.487294,2.317836,2.045823e-02,NaN,1.689132
ENSMUSG00000000049,4.248771,0.670968,0.943911,0.710838,4.771848e-01,NaN,0.321313

In [4]:
joined = rna.join(norna, how='inner', lsuffix='_RNA', rsuffix='_noRNA')
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.068078,9.457235e-01,9.961099e-01,0.024236,1113.772188,0.006149,0.090487,0.067959,9.458185e-01,9.944408e-01,0.024192
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.644889,2.091264e-14,1.650742e-12,13.679591,161.147872,1.394208,0.182351,7.645723,2.077750e-14,1.570749e-12,13.682407
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.264598,2.060156e-01,6.826370e-01,0.686100,25.889980,0.546685,0.432254,1.264730,2.059680e-01,6.689568e-01,0.686200
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.317572,2.047261e-02,1.950173e-01,1.688827,17.905616,1.129467,0.487294,2.317836,2.045823e-02,NaN,1.689132
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.710761,4.772322e-01,NaN,0.321270,4.248771,0.670968,0.943911,0.710838,4.771848e-01,NaN,0.321313

In [5]:
rnaDE = rna[rna['padj'] < 0.1]
rnaDE.shape

(1167, 7)

In [6]:
nornaDE = norna[norna['padj'] < 0.1]
nornaDE.shape

(1179, 7)

In [7]:
joined['DE_RNA'] = joined['padj_RNA'] < 0.1
joined['DE_noRNA'] = joined['padj_noRNA'] < 0.1
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA,DE_RNA,DE_noRNA
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.068078,9.457235e-01,9.961099e-01,0.024236,1113.772188,0.006149,0.090487,0.067959,9.458185e-01,9.944408e-01,0.024192,False,False
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.644889,2.091264e-14,1.650742e-12,13.679591,161.147872,1.394208,0.182351,7.645723,2.077750e-14,1.570749e-12,13.682407,True,True
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.264598,2.060156e-01,6.826370e-01,0.686100,25.889980,0.546685,0.432254,1.264730,2.059680e-01,6.689568e-01,0.686200,False,False
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.317572,2.047261e-02,1.950173e-01,1.688827,17.905616,1.129467,0.487294,2.317836,2.045823e-02,NaN,1.689132,False,False
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.710761,4.772322e-01,NaN,0.321270,4.248771,0.670968,0.943911,0.710838,4.771848e-01,NaN,0.321313,False,False

In [8]:
joined['Compare'] = joined['DE_RNA'] == joined['DE_noRNA']
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA,DE_RNA,DE_noRNA,Compare
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.068078,9.457235e-01,9.961099e-01,0.024236,1113.772188,0.006149,0.090487,0.067959,9.458185e-01,9.944408e-01,0.024192,False,False,True
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.644889,2.091264e-14,1.650742e-12,13.679591,161.147872,1.394208,0.182351,7.645723,2.077750e-14,1.570749e-12,13.682407,True,True,True
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.264598,2.060156e-01,6.826370e-01,0.686100,25.889980,0.546685,0.432254,1.264730,2.059680e-01,6.689568e-01,0.686200,False,False,True
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.317572,2.047261e-02,1.950173e-01,1.688827,17.905616,1.129467,0.487294,2.317836,2.045823e-02,NaN,1.689132,False,False,True
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.710761,4.772322e-01,NaN,0.321270,4.248771,0.670968,0.943911,0.710838,4.771848e-01,NaN,0.321313,False,False,True

In [9]:
joined.to_csv('DESeq2_results_combined_p1_no_lfc.csv')

# Compare AdjP < 0.1, LFC > 0.1

In [10]:
rna = pd.read_csv('Space_uG_over_Space_1G_rRNA_LFC1.csv', index_col=0)
rna['logpvalue'] = -np.log10(rna['pvalue'])
rna.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,logpvalue
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.000000,1.000000e+00,1.000000e+00,-0.000000
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.096562,1.278990e-12,1.127941e-10,11.893133
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.033283,3.014714e-01,1.000000e+00,0.520754
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.112382,3.465368e-02,5.244899e-01,1.460251
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.604833,5.452902e-01,NaN,0.263372

In [11]:
norna = pd.read_csv('Space_uG_over_Space_1G_no_rRNA_LFC1.csv', index_col=0)
norna['logpvalue'] = -np.log10(norna['pvalue'])
norna.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,logpvalue
ENSMUSG00000000001,1113.772188,0.006149,0.090487,0.000000,1.000000e+00,1.000000e+00,-0.000000
ENSMUSG00000000028,161.147872,1.394208,0.182351,7.097331,1.271892e-12,1.121397e-10,11.895550
ENSMUSG00000000031,25.889980,0.546685,0.432254,1.033385,3.014238e-01,1.000000e+00,0.520822
ENSMUSG00000000037,17.905616,1.129467,0.487294,2.112621,3.463321e-02,5.240473e-01,1.460507
ENSMUSG00000000049,4.248771,0.670968,0.943911,0.604896,5.452484e-01,NaN,0.263406

In [12]:
joined = rna.join(norna, how='inner', lsuffix='_RNA', rsuffix='_noRNA')
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.000000,1.000000e+00,1.000000e+00,-0.000000,1113.772188,0.006149,0.090487,0.000000,1.000000e+00,1.000000e+00,-0.000000
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.096562,1.278990e-12,1.127941e-10,11.893133,161.147872,1.394208,0.182351,7.097331,1.271892e-12,1.121397e-10,11.895550
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.033283,3.014714e-01,1.000000e+00,0.520754,25.889980,0.546685,0.432254,1.033385,3.014238e-01,1.000000e+00,0.520822
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.112382,3.465368e-02,5.244899e-01,1.460251,17.905616,1.129467,0.487294,2.112621,3.463321e-02,5.240473e-01,1.460507
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.604833,5.452902e-01,NaN,0.263372,4.248771,0.670968,0.943911,0.604896,5.452484e-01,NaN,0.263406

In [13]:
rnaDE = rna[rna['padj'] < 0.1]
rnaDE.shape

(626, 7)

In [14]:
nornaDE = norna[norna['padj'] < 0.1]
nornaDE.shape

(626, 7)

In [15]:
joined['DE_RNA'] = joined['padj_RNA'] < 0.1
joined['DE_noRNA'] = joined['padj_noRNA'] < 0.1
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA,DE_RNA,DE_noRNA
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.000000,1.000000e+00,1.000000e+00,-0.000000,1113.772188,0.006149,0.090487,0.000000,1.000000e+00,1.000000e+00,-0.000000,False,False
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.096562,1.278990e-12,1.127941e-10,11.893133,161.147872,1.394208,0.182351,7.097331,1.271892e-12,1.121397e-10,11.895550,True,True
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.033283,3.014714e-01,1.000000e+00,0.520754,25.889980,0.546685,0.432254,1.033385,3.014238e-01,1.000000e+00,0.520822,False,False
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.112382,3.465368e-02,5.244899e-01,1.460251,17.905616,1.129467,0.487294,2.112621,3.463321e-02,5.240473e-01,1.460507,False,False
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.604833,5.452902e-01,NaN,0.263372,4.248771,0.670968,0.943911,0.604896,5.452484e-01,NaN,0.263406,False,False

In [16]:
joined['Compare'] = joined['DE_RNA'] == joined['DE_noRNA']
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA,DE_RNA,DE_noRNA,Compare
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.000000,1.000000e+00,1.000000e+00,-0.000000,1113.772188,0.006149,0.090487,0.000000,1.000000e+00,1.000000e+00,-0.000000,False,False,True
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.096562,1.278990e-12,1.127941e-10,11.893133,161.147872,1.394208,0.182351,7.097331,1.271892e-12,1.121397e-10,11.895550,True,True,True
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.033283,3.014714e-01,1.000000e+00,0.520754,25.889980,0.546685,0.432254,1.033385,3.014238e-01,1.000000e+00,0.520822,False,False,True
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.112382,3.465368e-02,5.244899e-01,1.460251,17.905616,1.129467,0.487294,2.112621,3.463321e-02,5.240473e-01,1.460507,False,False,True
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.604833,5.452902e-01,NaN,0.263372,4.248771,0.670968,0.943911,0.604896,5.452484e-01,NaN,0.263406,False,False,True

In [17]:
joined.to_csv('DESeq2_results_combined_p1_lfc1.csv')

# Compare AdjP < 0.05, no LFC cutoff

In [18]:
rna = pd.read_csv('Space_uG_over_Space_1G_rRNA_ADJP5.csv', index_col=0)
rna['logpvalue'] = -np.log10(rna['pvalue'])
rna.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,logpvalue
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.000000,1.000000e+00,1.000000e+00,-0.000000
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.096562,1.278990e-12,1.127941e-10,11.893133
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.033283,3.014714e-01,1.000000e+00,0.520754
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.112382,3.465368e-02,5.244899e-01,1.460251
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.604833,5.452902e-01,NaN,0.263372

In [19]:
norna = pd.read_csv('Space_uG_over_Space_1G_no_rRNA_ADJP5.csv', index_col=0)
norna['logpvalue'] = -np.log10(norna['pvalue'])
norna.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,logpvalue
ENSMUSG00000000001,1113.772188,0.006149,0.090487,0.000000,1.000000e+00,1.000000e+00,-0.000000
ENSMUSG00000000028,161.147872,1.394208,0.182351,7.097331,1.271892e-12,1.121397e-10,11.895550
ENSMUSG00000000031,25.889980,0.546685,0.432254,1.033385,3.014238e-01,1.000000e+00,0.520822
ENSMUSG00000000037,17.905616,1.129467,0.487294,2.112621,3.463321e-02,5.240473e-01,1.460507
ENSMUSG00000000049,4.248771,0.670968,0.943911,0.604896,5.452484e-01,NaN,0.263406

In [20]:
joined = rna.join(norna, how='inner', lsuffix='_RNA', rsuffix='_noRNA')
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.000000,1.000000e+00,1.000000e+00,-0.000000,1113.772188,0.006149,0.090487,0.000000,1.000000e+00,1.000000e+00,-0.000000
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.096562,1.278990e-12,1.127941e-10,11.893133,161.147872,1.394208,0.182351,7.097331,1.271892e-12,1.121397e-10,11.895550
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.033283,3.014714e-01,1.000000e+00,0.520754,25.889980,0.546685,0.432254,1.033385,3.014238e-01,1.000000e+00,0.520822
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.112382,3.465368e-02,5.244899e-01,1.460251,17.905616,1.129467,0.487294,2.112621,3.463321e-02,5.240473e-01,1.460507
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.604833,5.452902e-01,NaN,0.263372,4.248771,0.670968,0.943911,0.604896,5.452484e-01,NaN,0.263406

In [21]:
rnaDE = rna[rna['padj'] < 0.1]
rnaDE.shape

(626, 7)

In [22]:
nornaDE = norna[norna['padj'] < 0.1]
nornaDE.shape

(626, 7)

In [23]:
joined['DE_RNA'] = joined['padj_RNA'] < 0.1
joined['DE_noRNA'] = joined['padj_noRNA'] < 0.1
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA,DE_RNA,DE_noRNA
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.000000,1.000000e+00,1.000000e+00,-0.000000,1113.772188,0.006149,0.090487,0.000000,1.000000e+00,1.000000e+00,-0.000000,False,False
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.096562,1.278990e-12,1.127941e-10,11.893133,161.147872,1.394208,0.182351,7.097331,1.271892e-12,1.121397e-10,11.895550,True,True
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.033283,3.014714e-01,1.000000e+00,0.520754,25.889980,0.546685,0.432254,1.033385,3.014238e-01,1.000000e+00,0.520822,False,False
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.112382,3.465368e-02,5.244899e-01,1.460251,17.905616,1.129467,0.487294,2.112621,3.463321e-02,5.240473e-01,1.460507,False,False
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.604833,5.452902e-01,NaN,0.263372,4.248771,0.670968,0.943911,0.604896,5.452484e-01,NaN,0.263406,False,False

In [24]:
joined['Compare'] = joined['DE_RNA'] == joined['DE_noRNA']
joined.head()

,baseMean_RNA,log2FoldChange_RNA,lfcSE_RNA,stat_RNA,pvalue_RNA,padj_RNA,logpvalue_RNA,baseMean_noRNA,log2FoldChange_noRNA,lfcSE_noRNA,stat_noRNA,pvalue_noRNA,padj_noRNA,logpvalue_noRNA,DE_RNA,DE_noRNA,Compare
ENSMUSG00000000001,1113.771453,0.006161,0.090505,0.000000,1.000000e+00,1.000000e+00,-0.000000,1113.772188,0.006149,0.090487,0.000000,1.000000e+00,1.000000e+00,-0.000000,False,False,True
ENSMUSG00000000028,161.147341,1.394221,0.182373,7.096562,1.278990e-12,1.127941e-10,11.893133,161.147872,1.394208,0.182351,7.097331,1.271892e-12,1.121397e-10,11.895550,True,True,True
ENSMUSG00000000031,25.889947,0.546701,0.432312,1.033283,3.014714e-01,1.000000e+00,0.520754,25.889980,0.546685,0.432254,1.033385,3.014238e-01,1.000000e+00,0.520822,False,False,True
ENSMUSG00000000037,17.905605,1.129479,0.487354,2.112382,3.465368e-02,5.244899e-01,1.460251,17.905616,1.129467,0.487294,2.112621,3.463321e-02,5.240473e-01,1.460507,False,False,True
ENSMUSG00000000049,4.248780,0.670981,0.944032,0.604833,5.452902e-01,NaN,0.263372,4.248771,0.670968,0.943911,0.604896,5.452484e-01,NaN,0.263406,False,False,True

In [25]:
joined.to_csv('DESeq2_results_combined_p5.csv')